### PR TITLE
Fix build, for real this time

### PR DESCRIPTION
**Pull request by tilk**
Always run the affected workflow before merging. Always run the affected workflow before merging. Always run the affected workflow before merging. Always run the affected workflow before merging.

Summary of the comments: `UnalignedFetcher` sometimes fetches one additional cache line beyond the ones that contain the code. Not really a big problem, but the core freezes on the bus error that can then happen. To work around this issue, an additional cache line is added to code segments.

### CODE REVIEW

**Comment by tilk** [comment]
Looks like this try was misguided. I objdumped the failing tests, and it looks like the core is still somehow trying to fetch data just outside the code segment. In both test programs, the last instruction is compressed `ret`, which is very close to the cache line boundary. I believe it's the `UnalignedFetcher` which makes the additional, unneeded request.

**Comment by tilk** [comment]
I think that the right way to proceed is to stop crashing the simulation when accessing stuff outside of the defined memory ranges. The `UnalignedFetcher` does some speculative prefetching, and prefetching outside of a memory range is not a failure.

**Comment by tilk** [comment]
This didn't help, either. The core freezes. Looks like fixing this properly requires some proper debugging. I think that, for now, we should just work around the issue.

**Comment by tilk** [comment]
Finally, benchmarks work again. The temporary workaround is to add one more cache line to the code segment.

**Review by lekcyjna123 — APPROVED** [review]

**Review by piotro888 — APPROVED** [review]

**Pull request merged**
