### PR TITLE
Autumn cleaning part 1 - move transactron

### PR DESCRIPTION
**Pull request by lekcyjna123**
Hi,

The new semester is coming so it is good time to start cleaning our repository. This is the first commit to implement #446. I have moved transactron from coreblocks/transactions to transactron directory to allow in future for the easier separation of transactron to its own project/repository. This move required to update all transactron imports in coreblocks and tests directories.

When this MR will be accepted my next step will by to split transactron/lib.py to smaller parts.

### CODE REVIEW

**Comment by Kristopher38** [comment]
If you're already moving this out of the `coreblocks` directory tree, why not go all the way through and split it into a separate submodule?

**Comment by lekcyjna123** [comment]
If you create separate submodule, then you have to crate separate review for transactron and its lib and for coreblocks. Whats more it will be hard to manage dependencies between them. So as long as transactron is developed rapidly I would prefer to leave it in coreblocks.

**Comment by lekcyjna123** [comment]
> There are still dependencies from Transactron to Coreblocks.

Yes this is expected. I wanted to use small steps principle to allow for easy review of code. Here I simply drag and drop transactron code, only with changes which are required to don't have regression. Whole cleaning will be in next PRs.

**Review by tilk — APPROVED** [review]

**Review by Kristopher38 — APPROVED** [review]
> If you create separate submodule, then you have to crate separate review for transactron and its lib and for coreblocks.

Well this is kind of expected when you work with submodules but I'm not so sure it hinders the work that much.

>Whats more it will be hard to manage dependencies between them.

The point is to have transactron be its own separate lib not dependent on coreblocks though (unless you meant something else).

>So as long as transactron is developed rapidly I would prefer to leave it in coreblocks.

Is it though? @tilk what do you think?

**Comment by tilk** [comment]
> Is it though? @tilk what do you think?

Ultimately, I want it to be a separate lib outside of Coreblocks. I have nothing against a small steps approach: let's first prepare for this separation, and later separate using one simple commit.

**Pull request merged**
