### PR TITLE
Make Collector a method combinator

### PR DESCRIPTION
**Pull request by tilk**
Collector was supposed to be in the combinator section of the lib, and conform to the combinator interface. Somehow, this wasn't enforced on code review. This PR fixes that.

### CODE REVIEW

**Comment by lekcyjna123** [comment]
Could you please point what was changed in code? I see that only variable names have been changed. Or I have missed something?
obraz

**Comment by tilk** [comment]
> Could you please point what was changed in code? I see that only variable names have been changed. Or I have missed something? obraz

That's exactly what was changed.

**Comment by lekcyjna123** [comment]
Thanks. I understand it now. I have though, that it wasn't conform to the combinator interface in implementation, not in way of variable naming.

**Comment by tilk** [comment]
> Thanks. I understand it now. I have though, that it wasn't conform to the combinator interface in implementation, not in way of variable naming.

This might be formalized later using protocols or ABCs, but first #201 should be merged. Also, let's see what happens in #209, where this PR should get used.

**Review by speederking07 — APPROVED** [review]
I have not seen any bugs

**Pull request merged**
