### PR TITLE
Fix pipeline

### PR DESCRIPTION
**Pull request by lekcyjna123**
It looks like we use too old amaranth and our pipeline fails to install it:
https://github.com/kuznia-rdzeni/coreblocks/actions/runs/6323098696/job/17169995647?pr=460

The solution is to update amaranth, but this cause some other issues, which we have to debug.

### CODE REVIEW

**Comment by Kristopher38** [comment]
Have you tried to debug why this actually happened? If so, what have you found out?

btw we're not ready to update amaranth yet, as fixes for https://github.com/amaranth-lang/amaranth/issues/790 are not there yet (unless we bodge our own workaround).

**Comment by lekcyjna123** [comment]
I haven't had time to debug this yet. I will try to do this tomorrow.

> btw we're not ready to update amaranth yet, as fixes for https://github.com/amaranth-lang/amaranth/issues/790 are not there yet (unless we bodge our own workaround).

Hmm. So maybe I will look for a other way to fix this pipeline issue. Maybe downgrade of pip will help.

**Comment by tilk** [comment]
> btw we're not ready to update amaranth yet, as fixes for https://github.com/amaranth-lang/amaranth/issues/790 are not there yet (unless we bodge our own workaround).

I think we can upgrade just fine, we just keep using Records as before. The Amaranth update must be done with care though - implemented RFCs must be read and type stubs updated.

**Comment by tilk** [comment]
Tried to do required changes, but somehow some tests broke. This requires investigation. See https://github.com/kuznia-rdzeni/coreblocks/pull/462

**Comment by lekcyjna123** [comment]
It is interesting that regression using cocotb passed, only unit tests failed. List of failing modules:
- ICache
- CSR
- Exception
- MemoryBank
- Core (both asm and random)

Particularly this last module is fully tested by cocotb, so I would rather say that there can be something in tests.

**Comment by lekcyjna123** [comment]
In exception unit there was a problem, that after update `rob_id - rob_start_idx` had signed(8) shape, what caused wrong comparison results in some cases.

**Comment by lekcyjna123** [comment]
I have created a minimal example which points to problems of Amaranth with simulation memory. This can explain why ICache, MemoryBank and Core fails. Issue has been reported here: https://github.com/amaranth-lang/amaranth/issues/922

**Comment by tilk** [comment]
Found another change in Amaranth's behavior, I believe it to be a bug and reported it: https://github.com/amaranth-lang/amaranth/issues/926

**Comment by tilk** [comment]
I took the liberty to clean up this PR for merging, as it's super-extra-blocking.

**Review by piotro888 — APPROVED** [review]

**Pull request merged**
